[Service]
Host = "0.0.0.0"
Port = 50003
ConnectRetries = 3
Labels = []
OpenMsg = "device snmp started"
MaxResultCount = 50000
Timeout = 5000
EnableAsyncReadings = true
AsyncBufferSize = 16

[Registry]
Host = "0.0.0.0"
Port = 8500
CheckInterval = "10s"
FailLimit = 3
FailWaitTime = 10
Type = "consul"

[Logging]
EnableRemote = false
File = "./device-snmp.log"
Level = "DEBUG"

[Clients]
  [Clients.Data]
  Name = "edgex-core-data"
  Protocol = "http"
  Host = "0.0.0.0"
  Port = 48080
  Timeout = 5000

  [Clients.Metadata]
  Name = "edgex-core-metadata"
  Protocol = "http"
  Host = "0.0.0.0"
  Port = 48081
  Timeout = 5000

  [Clients.Logging]
  Name = "edgex-support-logging"
  Protocol = "http"
  Host = "0.0.0.0"
  Port = 48061

[Device]
  DataTransform = true
  InitCmd = ""
  InitCmdArgs = ""
  MaxCmdOps = 128
  MaxCmdValueLen = 256
  RemoveCmd = ""
  RemoveCmdArgs = ""

# Pre-define Devices
# [[DeviceList]]
#   Name = "Snmp-device01"
#   Profile = "temperature and humidity sensor profile"
#   Description = "Example of Snmp Device"
#   Labels = [ "industrial" ]
#   [DeviceList.Protocols]
#     [DeviceList.Protocols.snmp]
#       Address = "127.0.0.1"
#       Port = "161"
#   [[DeviceList.AutoEvents]]
#     Frequency = "30s"
#     OnChange = false
#     Resource = "value"